version: '2'

services:
  python:
    tty: true # Enables debugging capabilities when attached to this container.
    image: oa/extract:latest
    network_mode: "host"
    ports:
      - 8000:8000
  mariadb:
    image: oa/datalake:latest
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: "host"
    volumes:
      - ./data:/bitnami/mariadb

